# Generated by Django 2.0 on 2019-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=50)),
                ('no_of_products', models.CharField(max_length=50)),
                ('manfacture_date', models.DateField(max_length=50)),
                ('expiry_date', models.DateField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
